### ISSUE TITLE
Consolidate public schema.

### ISSUE THREAD

**Issue by humlab** [humlab-sead/sead_change_control#1]
[ x ] Setup sqitch project

Compare the different SEAD versions for schema changes, excluding bugs-related data.
Create a DDL change (using sqitch) for each identified difference.

**Comment by roger-mahler** [comment]
This is is resolved by the total set of SEAD change control system (SCCS) change requests  that have been added to this repository. Any remaining issues previously resolved will be added as new change requests i.e. the current change set is defined as the October 2019 release.
