### ISSUE TITLE
Namnsättning av filter: Bibligraphy vs Bibliography

### ISSUE THREAD

**Issue by Maanin00** [humlab-sead/sead_change_control#105]
![image](https://user-images.githubusercontent.com/100921064/214305173-d631df2d-f800-4d78-8196-1f94d24bd6b6.png)

Tre filter innehåller "Bibligraphy", borde inte det stavas "Bibliography"?

**Comment by johanvonboer** [comment]
Yes. Texten kommer från databasen och behöver ändras där, vilket gör att denna issuen tillhör sead_change_control, så flyttat den dit.

**Comment by roger-mahler** [comment]
Deployed to staging.
