### ISSUE TITLE
10 meter ceramic shards

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_change_control#107]
In site 3540:
https://browser.sead.se/site/3540

We have ceramic shards labeled as 'Kärl' that is 10 meters in size?? I suspect the wrong unit of measurement is being used.
![image](https://user-images.githubusercontent.com/34707290/217490149-48c5b690-778d-48c7-8e84-b98d1090706d.png)

**Comment by MattiasSealander** [comment]
Yes, most likely the id used in import was set wrong, either by excel shenanigans or by myself. Will investigate if it is one off or consistent and add to pile of updates.

**Comment by MattiasSealander** [comment]
I looked this up and I am wondering where the data is fetched from and how. 

I put together a query below for the sample in the screenshot and that shows the unit of measurements as millimetres:

> SELECT
ps.physical_sample_id,
ps.sample_name,
d.dimension_name,
sd.dimension_value,
u.unit_name

> FROM tbl_physical_samples ps

> JOIN tbl_sample_dimensions sd ON ps.physical_sample_id = sd.physical_sample_id
> JOIN tbl_dimensions d ON sd.dimension_id = d.dimension_id
> JOIN tbl_units u ON d.unit_id = u.unit_id

> Where ps.sample_name like '4751@1@Kärl'

**Comment by johanvonboer** [comment]
You're right, the database is correct and I see now that I have made a mistake in how I fetch this data.

I am currently doing tbl_physical_samples => tbl_sample_dimensions => tbl_methods => tbl_units

But I should be doing tbl_physical_samples => tbl_sample_dimensions => tbl_dimensions => tbl_units

So I'm fetching the unit based on the method, when I should be fetching it based on the dimension.

I will correct this ASAP.

**Comment by MattiasSealander** [comment]
Has this been fixed so we can close this issue?

**Comment by johanvonboer** [comment]
It was semi-fixed, but it is fully fixed now, so yes we can close this.
