### ISSUE TITLE
20240602_DML_MAL_CONTACT_UPDATE.: Outdated contact information.

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_change_control#108]
From https://supersead.humlab.umu.se/site/2400

![image](https://user-images.githubusercontent.com/34707290/225868337-8986d6a2-4c06-4515-833c-5fe0e5862972.png)

The link http://www.idesam.umu.se/om/personal/visa-person/?uid=phbu0001&guise=anst1 doesn't work anymore.

**Comment by visead** [comment]
Update to: https://www.umu.se/en/staff/philip-buckland/

**Comment by roger-mahler** [comment]
Change request: [20240602_DML_MAL_CONTACT_UPDATE](https://github.com/humlab-sead/sead_change_control/blob/master/mal/deploy/20240602_DML_MAL_CONTACT_UPDATE.sql).

**Comment by roger-mahler** [comment]
Deployed to staging.
