### ISSUE TITLE
composite chronology gone?

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_change_control#109]
There used to be an analysis method called "composite chronology", this is now gone from the database. Should that be so?

**Comment by roger-mahler** [comment]
This is solved in [20220916_DDL_RESULTS_CHRONOLOGY](https://github.com/humlab-sead/sead_change_control/blob/master/general/deploy/20220916_DDL_RESULTS_CHRONOLOGY.sql) and is currently in staging,
