### ISSUE TITLE
Tool tip text lacks explanation for several filters

### ISSUE THREAD

**Issue by Maanin00** [humlab-sead/sead_change_control#114]
**Describe the bug**
The following filters lack explanatory tool tip:

Region
Proxy types
Feature type
Bibligraphy modern
Bibligraphy sites/Samplegroups
Bibligraphy sites
Data types
RDB system
RDB Code
Modification Types
Abundance Elements
Sampling Context
Construction types
abundance classification
Abundances

**Comment by johanvonboer** [comment]
Just to clarify, it's about these:
https://user-images.githubusercontent.com/34707290/237050237-0e862df8-7b88-4dfb-a78f-113cb124c602.png

**Comment by roger-mahler** [comment]
Closing dupliacte.
