### ISSUE TITLE
20240602_DML_RRB_KOCH_UPDATE.: Koch ecocode definitions lack name

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_change_control#116]
This ecocode has no name, only an abbreviation.
![image](https://user-images.githubusercontent.com/34707290/234615843-992cc773-1c1b-4281-a969-506bc0034c90.png)

**Comment by johanvonboer** [comment]
Phil will send a request for name

**Comment by visead** [comment]
FNoDi - eats Dipterous larvae  = larval dipterophagous
FNoMi – eats mites  = Acarophagous

**Comment by roger-mahler** [comment]
```sql
update tbl_ecocode_definitions set name = 'larval dipterophagous' where abbreviation = 'FNoDi';
update tbl_ecocode_definitions set name = 'Acarophagous' where abbreviation = 'FNoDi';
```

**Comment by roger-mahler** [comment]
Change request: [20240602_DML_RRB_KOCH_UPDATE](https://github.com/humlab-sead/sead_change_control/blob/master/bugs/deploy/20240602_DML_RRB_KOCH_UPDATE.sql).

**Comment by roger-mahler** [comment]
There are in total 125 records having null value in `definition":

```sql
select s.name, d.abbreviation, d.definition, d.name, d.notes
from tbl_ecocode_definitions d
join tbl_ecocode_groups using (ecocode_group_id)
join tbl_ecocode_systems s using (ecocode_system_id)
where d.definition is null;
```

**Comment by roger-mahler** [comment]
Deployed to staging. No ecocode definitions lack name after update.
