### ISSUE TITLE
High abundance counts

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_change_control#120]
There are some very high abundance counts
![image](https://github.com/humlab-sead/sead_change_control/assets/34707290/654ec15c-6e9b-4f71-9937-b60f9eb6e109)

Most notably the count of 8351, this belongs to site 2561: https://supersead.humlab.umu.se/site/2561

Is this correct? Is it feasible that such a high count can exist?

**Comment by johanvonboer** [comment]
@visead looks into it.

@johanvonboer get site_id + site name + alternative identifiers for sample names, etc.

**Comment by visead** [comment]
Have checked the Skidmore one. Is correct.

Phil

________________
Philip Buckland
Umeå University
Sweden
________________________________

**Comment by johanvonboer** [comment]
Thank you, I think we can close this then.
