### ISSUE TITLE
When selecting Sweden in the country filter, a site in Denmark is also shown.

### ISSUE THREAD

**Issue by Maanin00** [humlab-sead/sead_change_control#125]
When selecting Sweden in the country filter, a site in Denmark is also shown. Site name: Lindved. Is this correct? 

![image](https://github.com/humlab-sead/sead_change_control/assets/100921064/01b14061-24b3-4f4f-819e-472340ac8d47)

**Comment by johanvonboer** [comment]
Message from @visead: "It's an error in Bugs. Will be updated in next Access update."
