### ISSUE TITLE
Biblio sometimes loads publication year twice

### ISSUE THREAD

**Issue by Loer0022** [humlab-sead/sead_change_control#127]
Sometimes in SuperSEAD when looking in the dataset and site reference section there are some references that has two years provided in brackets, e.g. Allison, E.P. (2003) (2003). I checked the metadata in tbl_biblio and there aren’t any doubles there so it must be how data is being collected and presented in the web browser.

However, this isn’t an issue for all references in the browser. I put some example sites below.

Double
https://browser.sead.se/site/3208
https://browser.sead.se/site/2918
https://browser.sead.se/site/2950

Not an issue
https://browser.sead.se/site/3673
https://browser.sead.se/site/3677
https://browser.sead.se/site/382

**Comment by roger-mahler** [comment]
Change request: [20240327_DML_FACET_ISSUE_127](https://github.com/humlab-sead/sead_change_control/blob/master/facet/deploy/20240327_DML_FACET_ISSUE_127.sql).
