### ISSUE TITLE
Suggestion: Rename facet 'Master datasets' to...

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_change_control#131]
'Dataset provider'

Because that seems to be what they are? And would be more understandable for other people

**Comment by roger-mahler** [comment]
Change request: [20240530_DML_DATASET_PROVIDERS](https://github.com/humlab-sead/sead_change_control/blob/master/facet/deploy/20240530_DML_DATASET_PROVIDERS.sql).

**Comment by roger-mahler** [comment]
Deployed to staging.
