### ISSUE TITLE
20231120_DML_DENDRO_LOOKUP: New dendro lookup data (20200630 dataset)

### ISSUE THREAD

**Issue by MattiasSealander** [humlab-sead/sead_change_control#136]
New lookup data for the latest dendro import needs to be added before ingestion. The lookup data, with inserts, can be found in the attached excel file. 

[dendro_building_lookup_inserts_20231019.xlsx](https://github.com/humlab-sead/sead_change_control/files/13224651/dendro_building_lookup_inserts_20231019.xlsx)

**Comment by roger-mahler** [comment]
Added system IDs: 
[dendro_building_lookup_inserts_20231019_with_ids.xlsx](https://github.com/humlab-sead/sead_change_control/files/13447225/dendro_building_lookup_inserts_20231019_with_ids.xlsx)

**Comment by roger-mahler** [comment]
Change project: [dendrochronology](https://github.com/humlab-sead/sead_change_control/blob/master/dendrochronology/sqitch.plan)
Change request: [20231120_DML_DENDRO_LOOKUP](https://github.com/humlab-sead/sead_change_control/blob/master/dendrochronology/deploy/20231120_DML_DENDRO_LOOKUP.sql)
