### ISSUE TITLE
20220916_DDL_RESULTS_CHRONOLOGY: analysis_entity_ages is empty

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_change_control#17]

**Comment by roger-mahler** [comment]
More explanation needed please.

**Comment by johanvonboer** [comment]
Table is literally empty. Data in this table is needed for mapping sites to time-spans, which is needed for the timeline to function.

**Comment by visead** [comment]
Phil will sketch code to extract oldest and youngest date for each sample from tbl_geochronologies, relative ages and other things...

**Comment by visead** [comment]
Phil and Francesca are working on this, but there is a lot of data cleaning and lookup data collation to do. This is also needed for the SLW and Networks analysis, so scheduled for 2020.03

**Comment by roger-mahler** [comment]
Resolved in [20220916_DDL_RESULTS_CHRONOLOGY](https://github.com/humlab-sead/sead_change_control/blob/master/general/deploy/20220916_DDL_RESULTS_CHRONOLOGY.sql).
Also related to #92 and #93.

**Comment by roger-mahler** [comment]
Change request: [20220916_DDL_RESULTS_CHRONOLOGY_LOOKUPS](https://github.com/humlab-sead/sead_change_control/blob/master/bugs/deploy/20220916_DDL_RESULTS_CHRONOLOGY_LOOKUPS.sql).
