### ISSUE TITLE
Incorrect column name in queries to ecocode_definitions

### ISSUE THREAD

**Issue by visead** [humlab-sead/sead_change_control#21]
tbl_ecocode_definitions.label needs to be changed to tbl_ecocode_definitions.name

Affects supersead facet queries.

Results from column name change between sead master 8 and 9.

**Comment by visead** [comment]
not fixed - check database version for supersead?

**Comment by roger-mahler** [comment]
This is fixed by commit /sead_change_control/commit/7d03e796f932c648a55e8246b51c3053bd1c8204 but not yet released.
