### ISSUE TITLE
tbl_dataset_submissions field constraint update

### ISSUE THREAD

**Issue by MattiasSealander** [humlab-sead/sead_change_control#219]
Currently the "date_submitted" field is restricted to only accept date formats, and not allowed to be NULL. The 2023-12 dendro import features instances where the sampling date is only identified to a year, or instances where the contact person for sampling is known, but date is unknown. 

In order to import this data the field would need to be updated to string and accept NULL values.

**Comment by roger-mahler** [comment]
Resolved by #228 (https://github.com/humlab-sead/sead_change_control/commit/f7058d482966021446f57b4fd7b0aa7ae7a6db44)
