### ISSUE TITLE
MS and 550 prep-method seems to have a reversed link

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_change_control#227]
Regarding the analysis method Magnetic susceptibility; here the sample weights are measured pre-burning and then after being burnt. 

It seems that the AEs that are NOT connected to the 550-prepMethod (method_id 82) are actually the ones that are burned. This seems counter-intuitive.

This SQL demonstrates the problem, it shows that it is the analysis_entity with the heavier weight that has the prep method 550:

```SQL
SELECT
*
FROM tbl_physical_samples
JOIN tbl_analysis_entities ON tbl_analysis_entities.physical_sample_id=tbl_physical_samples.physical_sample_id
JOIN tbl_datasets ON tbl_datasets.dataset_id=tbl_analysis_entities.dataset_id
JOIN tbl_methods ON tbl_methods.method_id=tbl_datasets.method_id
JOIN tbl_measured_values ON tbl_measured_values.analysis_entity_id=tbl_analysis_entities.analysis_entity_id
LEFT JOIN tbl_analysis_entity_prep_methods ON tbl_analysis_entity_prep_methods.analysis_entity_id=tbl_analysis_entities.analysis_entity_id
WHERE tbl_physical_samples.physical_sample_id=3778 AND tbl_methods.method_id=33
```

Should this not be reversed so that the analysis_entity with the lesser weight that is connected to the 550 prep method (burned), and the AE with the higher weight should NOT be connected to the prep method to indicate that is was unburnt?

**Comment by johanvonboer** [comment]
This SQL shows that it is the analysis_entity with the heavier weight that has the prep method 550:

```SQL
SELECT
*
FROM tbl_physical_samples
JOIN tbl_analysis_entities ON tbl_analysis_entities.physical_sample_id=tbl_physical_samples.physical_sample_id
JOIN tbl_datasets ON tbl_datasets.dataset_id=tbl_analysis_entities.dataset_id
JOIN tbl_methods ON tbl_methods.method_id=tbl_datasets.method_id
JOIN tbl_measured_values ON tbl_measured_values.analysis_entity_id=tbl_analysis_entities.analysis_entity_id
LEFT JOIN tbl_analysis_entity_prep_methods ON tbl_analysis_entity_prep_methods.analysis_entity_id=tbl_analysis_entities.analysis_entity_id
WHERE tbl_physical_samples.physical_sample_id=3778 AND tbl_methods.method_id=33
```

Should this not be reversed so that the analysis_entity with the lesser weight that is connected to the 550 prep method (burned), and the AE with the higher weight should NOT be connected to the prep method to indicate that is was unburnt?

**Comment by johanvonboer** [comment]
@MattiasSealander Phil suggested that perhaps you could have a look at this?

**Comment by MattiasSealander** [comment]
Can do, looked into this issue on prep methods when I started.

**Comment by MattiasSealander** [comment]
Hey,

So I think it works as intended. Measured values stores the MS result, which should increase after being burnt at 550 degrees (provided it has not already been affected by burning prehistorically etc.). The sample volumes should be stored in tbl_sample_dimensions if I remember this correctly. The below SQL has added in the dimensions table. The weight does not necessarily change after burning, if it is mostly minerogenic. If it has a lot of organic content, then this would burn away most and the weight should change. But that has to do with Loss on Ignition. 

I am uncertatin if the Loss on Ignition value in this case would mean that the weight changed, but perhaps has not been updated for the sample then, for the prep method? If you understand what I mean.

```
SELECT`
ps.physical_sample_id,
d.dataset_id,
aep.analysis_entity_prep_method_id,
m.method_name,
mv.measured_value as "MS value",
dn.dimension_name,
dn.dimension_description,
sd.dimension_value as "Weight"

FROM tbl_physical_samples ps
JOIN tbl_sample_dimensions sd ON ps.physical_sample_id = sd.physical_sample_id
JOIN tbl_dimensions dn ON sd.dimension_id = dn.dimension_id
JOIN tbl_analysis_entities ae ON ae.physical_sample_id = ps.physical_sample_id
JOIN tbl_datasets d ON d.dataset_id = ae.dataset_id
JOIN tbl_methods m ON m.method_id = d.method_id
JOIN tbl_measured_values mv ON mv.analysis_entity_id = ae.analysis_entity_id
LEFT JOIN tbl_analysis_entity_prep_methods aep ON aep.analysis_entity_id = ae.analysis_entity_id

WHERE ps.physical_sample_id = 3352
```

**Comment by MattiasSealander** [comment]
So in the above the "volume" is not a substitute for weight. I spoke to Samuel to see if he remembered entering the "raw data" (i.e. the weights on which stuff like LOI (proportion of organic content in a sample) is calculated. He said that as far as he can remember they never entered that data. So, that means there are no weights for soil samples in SEAD. 

So it seems that the prep method works as intended, as the MS value should increase after subjecting it to burning at 550 degrees, if it has not already been altered or is rich in iron etc. There are some LOI values that have the prep method as well, but Samuel mentioned that not all LOI values are calculated using burning at 550 degrees, but some may be at lower heat etc. This Phil will need to confirm, as I do not know if we have that information then in such a case.

**Comment by johanvonboer** [comment]
Of course, I realize now that I am just confusing MS and LOI with each other. Thanks for looking into this and the explanation!

**Comment by johanvonboer** [comment]
So, just to clarify, the chart that today looks like this:
![image](https://github.com/humlab-sead/sead_change_control/assets/34707290/fcdd4e21-b7fa-4ac5-b1a1-57fb56a79445)

Should actually look like this?
![image](https://github.com/humlab-sead/sead_change_control/assets/34707290/74a718d3-e4fc-4ceb-b586-20fcd43e92fc)

**Comment by MattiasSealander** [comment]
Do you have a Site ID for this one? Difficult to say without context. High increase following burning would suggest the soils mirror the natural background, but if it is high before and after then that may indicate humans had been heating the soils in the past.

**Comment by johanvonboer** [comment]
This is from https://browser.sead.se/site/1

**Comment by MattiasSealander** [comment]
It should be correct. I can't say 100% without the raw data itself, but a burned sample should result in higher values than an unburned (for MS). And if the change is minimal after burning, or pretty much the same, that may indicate an anomaly that possibly is linked to human activity.

**Comment by johanvonboer** [comment]
So, the best thing would be to sort this chart based on the difference between burned and unburned?
