### ISSUE TITLE
Dendrochronology record type needed

### ISSUE THREAD

**Issue by visead** [humlab-sead/sead_change_control#23]
Dendrochronology data needs a record type to enable some query and filter functionality.

tbl_record_types.record_name = 'Dendrochronology'
tbl_record_types.record_name = SEE ROGER'S QUERY

Update tbl_methods.record_type_id to match the new record_type

**Comment by roger-mahler** [comment]
Create Change Request as follows:

```sql
insert into tbl_record_types (record_type_id, record_type_name, record_type_description) values (20, 'Dendrochronology', 'Detemination of age through tree ring measurements');

update tbl_methods set record_type_id = 20 where method_id = 10 and method_abbrev_or_alt_name = 'Dendro'

```

**Comment by roger-mahler** [comment]
See changes in [this](https://github.com/humlab-sead/sead_change_control/commit/06968c9ee1df1cc7beea1e377276ce4f4b3b4ecc) commit.
