### ISSUE TITLE
Integration of temperature proxy data

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_change_control#24]
Timeline needs temperature data in the database. I have created the table tbl_temperatures for this purpose, but it should be integrated into the sead change control so that it carries over with different database versions. The name is also wrong since according to Phil this is not actually temperature data but only a proxy for it. Perhaps this data should also be inserted into an existing table somewhere rather than having it's own? If you don't mind I'll leave it up to you @visead and @roger-mahler to figure out where/how to best integrate this data into the SEAD database in a more proper manner.

Attaching SQL for creating the table and inserting the data.

[tbl_temperatures.zip](https://github.com/humlab-sead/sead_change_control/files/3944969/tbl_temperatures.zip)

**Comment by visead** [comment]
At the moment I just envision the climate data as a background image to help users orient themselves in time. The temporary solution is a good workaround.

However, these are essentially isotope data, and could be stored in SEAD. I would also be useful for users to search using the data (e.g. insects when isotopes show cold). I'll need to contact the data creators to check this is OK (should be as published open source data).

Something for next year.

**Comment by roger-mahler** [comment]
Closing this issue for now.
