### ISSUE TITLE
Filter has corrupt name

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_change_control#25]
Filter with facetCode "tbl_denormalized_measured_values_37" has a DisplayTitle of "P┬░", which is obviously due to some sort of encoding translation error.

**Comment by roger-mahler** [comment]
Resolved by https://github.com/humlab-sead/sead_change_control/commit/d93f0d2ae5716b0713018a5dbf98f8130724722d

**Comment by roger-mahler** [comment]
See sead_api/deploy/20190101_DDL_FACET_SCHEMA.sql
