### ISSUE TITLE
Dendro-datat har överflödiga citattecken runt många strängar

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_change_control#252]
Här är ett exempel där jag väljer ut data från site 1 (en MAL site som ser normal ut) och site 3998 som är en dendro-site:
```SQL
SELECT 
tbl_sites.site_id,
tbl_sites.site_name, 
tbl_sample_groups.sample_group_name
FROM tbl_sites 
JOIN tbl_sample_groups ON tbl_sample_groups.site_id=tbl_sites.site_id
WHERE tbl_sites.site_id IN (1, 3998);
```

Resultatet är att dendro-datat har citat-tecken runt sina strängar (borde inte finnas):
![image](https://github.com/humlab-sead/sead_change_control/assets/34707290/aafd9868-0d02-4e6d-8c90-9b843a9ac6e1)

Problemet är inte begränsat till endast tbl_sites och tbl_sample_groups, utan det verkar gälla många textsträngar i dendro-datat, här är hur site datat för site 3998 ser ut i JSON-form:

![image](https://github.com/humlab-sead/sead_change_control/assets/34707290/c5aadd9c-2b27-4bb4-adc8-57f3c935d832)

**Comment by MattiasSealander** [comment]
I just ran Johans query against the staging database (202312) and the results still showed quotation marks around dendro data.

**Comment by MattiasSealander** [comment]
Great, so we can close this issue then?

**Comment by johanvonboer** [comment]
Yes, I think so
