### ISSUE TITLE
Region facet request

### ISSUE THREAD

**Issue by visead** [humlab-sead/sead_change_control#26]
Can we have a "Region" facet under the space-time group?

Contents would be something like (filtering sites?):
```sql
select location_name, site_id, location_type_id
from tbl_locations
inner join tbl_site_locations on tbl_locations.location_id=tbl_site_locations.location_id
where tbl_locations.location_type_id = 2 or tbl_locations.location_type_id = 7 or tbl_locations.location_type_id = 14 or tbl_locations.location_type_id = 16 or tbl_locations.location_type_id = 18
order by location_name
```
Use case: A point of entry for all sites in Västerbotten linked from https://sparfran10000ar.se/

**Comment by roger-mahler** [comment]
[20190101_DML_FACET_SCHEMA.sql](https://github.com/humlab-sead/sead_change_control/commit/10a6e07787c233f875665d2196795052d8036666#diff-0e042bcda70895ef2519a4ab554b83db769b409c03b0c7772c4b9001857e375f)
