### ISSUE TITLE
Filter for carbonised samples

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_change_control#266]
Requested by the plant macrofossil-department (Sofi).

**Comment by roger-mahler** [comment]
We do have a filter which can be used to filter out "Carbonised" records:

![image](https://github.com/humlab-sead/sead_change_control/assets/17061116/82511645-b6fd-4490-8088-9f31aa6a65bf)

**Comment by roger-mahler** [comment]
I guess we also could setup a copy of this filter and call it "Preservation type" instead.
