### ISSUE TITLE
20240604_DML_SAMPLE_GROUP_FACET: Incorrect amount of analysis_entities returned for facet query

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_change_control#301]
These three sample groups, all named 'Survey', all claim to have 104 analysis_entities associated with them. This is true for two of them, but not the third. The third belongs to site 131 and have many more analysis_entities.

![image](https://github.com/humlab-sead/sead_query_api/assets/34707290/2ff568b5-4f91-4f0e-883c-3f940506ed47)

https://supersead.humlab.umu.se/site/131

Assuming the 'count' returned by the endpoint is indeed the number of analysis entities.

**Comment by roger-mahler** [comment]
Change request: [20240604_DML_SAMPLE_GROUP_FACET](https://github.com/humlab-sead/sead_change_control/blob/master/facet/deploy/20240604_DML_SAMPLE_GROUP_FACET.sql).

**Comment by roger-mahler** [comment]
Site name has been added to displayed text to avoid ambiguity with duplicate sample group names. To avoid duplicated text, the site name are removed (if existst) from the sample group name. Result after update:

![image](https://github.com/humlab-sead/sead_change_control/assets/17061116/b8626b3d-8e13-43e9-9a6c-77438c46b9ba)

**Comment by roger-mahler** [comment]
Deployed to staging.
