### ISSUE TITLE
Dendro lookup ID 126 has the wrong name

### ISSUE THREAD

**Issue by MattiasSealander** [humlab-sead/sead_change_control#311]
In the staging cluster, the tbl_dendro_lookup ID 126 has the description set as its name. 

The name should be "Sapwood (Sp)", with the description being "Number of sapwood rings in a sample.". 

Currently, however, the description is set as its name, with an old version of the description. 

Name needs to be updated, and the current name moved to the description field. 

`UPDATE tbl_dendro_lookup SET description = 'Number of sapwood rings in a sample.' WHERE dendro_lookup_id = 126;`

`UPDATE tbl_dendro_lookup SET name = 'Sapwood (Sp)' WHERE dendro_lookup_id = 126;`

**Comment by roger-mahler** [comment]
Resolved by feb7efee0138d4b4707d096afc0ea9e89246aaf3.
change: backdated updates in CR (https://github.com/humlab-sead/sead_change_control/issues/153)  to CR (https://github.com/humlab-sead/sead_change_control/issues/148 and https://github.com/humlab-sead/sead_change_control/issues/153)
