### ISSUE TITLE
20241111_DDL_RESULTS_CHRONOLOGY: Additional data for tbl_analysis_entity_ages

### ISSUE THREAD

**Issue by rebeckahw** [humlab-sead/sead_change_control#315]
[Chronology_20240205.xlsx](https://github.com/user-attachments/files/16728016/Chronology_20240205.xlsx)

This file contains additional data for the table tbl_analysis_entity_ages.

**Comment by roger-mahler** [comment]
Change request: [20241111_DDL_RESULTS_CHRONOLOGY](https://github.com/humlab-sead/sead_change_control/blob/master/bugs/deploy/20241111_DDL_RESULTS_CHRONOLOGY.sql).

**Comment by roger-mahler** [comment]
Change request: [20241112_DDL_RESULTS_CHRONOLOGY_IMPORT_UDF](https://github.com/humlab-sead/sead_change_control/blob/master/utility/deploy/20241112_DDL_RESULTS_CHRONOLOGY_IMPORT_UDF.sql).
