### ISSUE TITLE
Correct Filter group and item titles

### ISSUE THREAD

**Issue by visead** [humlab-sead/sead_change_control#37]
**Correct filter visible elements as follows**:

measured_values - measurements
MS -Magnetic sus.
LOI - Loss on Ignition
PT? - Phosphates

space_time - space/time
Site - Sites
Country - Countries
Sample group - Sample groups

Taxa - Taxon

**Reorder filter groups:**
space/time
ecology
measurements
taxonomy

**Reorder items within space/time filter**
Master datasets
Countries
Sites
Sample groups
Time periods
Geochronology

**Comment by visead** [comment]
Is this solvable though [https://github.com/humlab-sead/sead_query_api/issues/53#issuecomment-567436980]? (sorry, don't know how to link between repositories!)

**Comment by roger-mahler** [comment]
Partly resolved b humlab-sead/sead_query_api/issues/53.

**Comment by roger-mahler** [comment]
See [20200203_DML_FACET_UI_ELEMENTS_UPDATE](https://github.com/humlab-sead/sead_change_control/blob/master/sead_api/deploy/20200203_DML_FACET_UI_ELEMENTS_UPDATE.sql) which resolves part of this issue.

**Comment by johanvonboer** [comment]
Still lacks sort order. Would like to have integers on both the groups and filters which denotes sort order.
