### ISSUE TITLE
Troublesome characters in methods description entry for  Swedish Rikets Nät

### ISSUE THREAD

**Issue by visead** [humlab-sead/sead_change_control#38]
Method description needs editing to remove linebreak between 'use.' and 'See' as it causes problem when exporting data.

"Swedish Rikets Nät (National Grid) system. Full name "RT 90 2.5 gon V 0:-15". X = south-north, Y = west-east. Essentially superceded by SWEREF 99 although still in extensive use.
See http://www.lantmateriet.se/templates/LMV_Page.aspx?id=4766&lang=EN (NOTE: include URL as biblio link)"

**Comment by roger-mahler** [comment]
One row affected:
```sql
select *
from tbl_methods
where description ~ '.*use\.\w*\n\w*See.*'
```
method id 69.
