### ISSUE TITLE
Bugs Sample codes need to be stored as alt refs in SEAD

### ISSUE THREAD

**Issue by visead** [humlab-sead/sead_change_control#42]
In BugsCEP, unique identifier for a sample is TSample.SampleCODE.
This is stored in bugs_trace during import but not stored in the main SEAD database.
SampleCODE needs storing in SEAD as:
tbl_sample_alt_refs.alt_ref with type "Database identifier" (new alt_ref_type)

This is needed for tracing samples through SEAD to Bugs, for example when Francesca creates a matrix of all insect samples.

**Comment by roger-mahler** [comment]
Solved by 47be10278e2cc5840a9e272ae38b40364ca4b0e2.

Note that this fix (for the time being) must be executed after each Bugs import.
