### ISSUE TITLE
tbl_measured_value_dimensions and tbl_analysis_entity_dimensions are empty

### ISSUE THREAD

**Issue by Loer0022** [humlab-sead/sead_change_control#43]
These two tables are currently empty and are not in use. The tables seem to be meant for another layer of storing information about subsamples and their measured dimensions e.g. before and after burning weights for LOI analysis. 

Although I think this function seem to exist indirectly in other populated tables, but I might be cofusing things.

Since they aren't in use and you can get sample information form other tables I would suggest looking into perhaps removing them

**Comment by Loer0022** [comment]
@Loer0022 @visead

**Comment by visead** [comment]
These provide the capacity for giving an analysis entity or measured value dimensions that are not covered by the sample dimensions. We might not need them, but should keep them in case the need arises.
