### ISSUE TITLE
MAL dataset Quality Assurance (part #1)

### ISSUE THREAD

**Issue by Loer0022** [humlab-sead/sead_change_control#45]
64 MAL sites in tbl_sites has missing or erroneous coordinates when reviewing SEAD master 9. These sites are somewhat misplaced with some being found in water and others remaining in the general area of their correct location. Of these 64 sites only 53 were corrected due to some sites currently missing metadata or lack coordinate information.

tbl_sites should be corrected with the following list below which has correct coordinates,

site_id | altitude | latitude_dd | longitude_dd | national_site_identifier | site_description | site_name | site_preservation_status_id | date_updated
-- | -- | -- | -- | -- | -- | -- | -- | --
57 | 15 | 56.8882889 | 12.5898222 | Skrea Raä 162 |   | Skrea Raä 162 |   | 2013-05-16 10:39:58.584644+02
78 |   | 55.5672222226 | 12.9844444 | MHM12753; MHM12879 |   | Citytunnelprojektet delområde 5 |   | 2013-11-13 15:33:32.218+01
84 |   | 55.5638888889 | 12.9794444 | MHM12878; MHM12752 |   | Citytunnelprojektet delområde 4 |   | 2013-11-13 15:33:32.218+01
85 |   | 68.6027777778 | 19.8483333 |   |   | Guomojávrrit |   | 2013-11-13 15:33:32.218+01
90 |   | 57.4808833337 | 12.6857750 | Örby 98:1 |   | Örby Raä 98 |   | 2013-11-13 15:33:32.218+01
97 |   | 70.4894444441 | 29.2500000 |   |   | Oarddojávri |   | 2013-11-13 15:33:32.218+01
100 |   | 70.3221555559 | 25.1738639 |   |   | Ruksesbákti, Indre Sandvik |   | 2013-11-13 15:33:32.218+01
105 |   | 55.5611111111 | 12.9716667 | MHM 12877 |   | Citytunnelprojektet delområde 3 |   | 2013-11-13 15:33:32.218+01
111 |   | 61.2238444448 | 11.4983500 |   |   | Melvold |   | 2013-11-13 15:33:32.218+01
119 |   | 59.1138888889 | 9.7980556 | 136604/136599 |   | Sundsaasen 2 |   | 2013-11-13 15:33:32.218+01
121 |   | 61.2758333337 | 11.6069444 |   |   | Tiertjern |   | 2013-11-13 15:33:32.218+01
122 |   | 55.9519444444 | 11.8752778 | NFH A2039 |   | Hilleröd NFH A2039 |   | 2013-11-13 15:33:32.218+01
123 |   | 70.6983333330 | 23.6280556 |   |   | Skjærvika |   | 2013-11-13 15:33:32.218+01
124 |   | 58.4809444448 | 13.4798472 | Ledsjö 153:1 |   | Ledsjö Raä 153 |   | 2013-11-13 15:33:32.218+01
128 |   | 55.1130555556 | 14.8705556 | BMR 3054 |   | BMR 3054 Vestre Indlæg |   | 2013-11-13 15:33:32.218+01
132 |   | 61.2220416670 | 11.4927944 |   |   | Stræten terasse |   | 2013-11-13 15:33:32.218+01
135 |   | 70.9619444444 | 26.6700000 |   |   | Sværholt |   | 2013-11-13 15:33:32.218+01
139 |   | 63.5861750 | 19.7208000 | Nordmaling 524:1 |   | Bothnia line JP 71F1 |   | 2013-11-13 15:33:32.218+01
143 |   | 61.3736111114 | 11.5144444 |   |   | Knubbetjern |   | 2013-11-13 15:33:32.218+01
153 |   | 61.3844444441 | 11.5433333 |   |   | Knubba |   | 2013-11-13 15:33:32.218+01
159 |   | 70.0669444445 | 27.5586111 |   |   | Láksjohka |   | 2013-11-13 15:33:32.218+01
163 |   | 58.1368305552 | 12.9879639 |   |   | Västerbitterna 3:17 |   | 2013-11-13 15:33:32.218+01
165 |   | 61.2266527781 | 11.4976694 |   |   | Rødstranda |   | 2013-11-13 15:33:32.218+01
176 |   | 63.5844444441 | 19.5839944 |   |   | Bothnia line JP 71C1/71:24 |   | 2013-11-13 15:33:32.218+01
178 |   | 60.5190944448 | 15.4388000 |   |   | Yttre Medväga |   | 2013-11-13 15:33:32.218+01
186 | 36 | 63.8449999997 | 20.1447222 | Umeå socken 229 |   | Prästsjödiket Umeå |   | 2013-11-13 15:33:32.218+01
193 |   | 63.7231278 | 20.1977083 |   |   | Bothnia line JP 73G |   | 2013-11-13 15:33:32.218+01
203 |   | 63.6594167 | 19.9786472 |   |   | Bothnia line JP 72E |   | 2013-11-13 15:33:32.218+01
209 |   | 63.2226500 | 18.0569333 |   |   | Bothnia line jp 31J1 |   | 2013-11-13 15:33:32.218+01
213 |   | 59.3803250 | 15.6283583 |   |   | Alväng, Götlunda |   | 2013-11-13 15:33:32.218+01
241 |   | 58.3846361108 | 13.8942833 | Skövde 158:1 |   | Skövde Raä 158 |   | 2013-11-13 15:33:32.218+01
243 |   | 61.3833333330 | 11.5288889 |   |   | Deset Knubben |   | 2013-11-13 15:33:32.218+01
254 | 20 | 63.3916194 | 19.2470694 | Grundsunda 30:1 |   | Grundsunda Raä 30 |   | 2013-11-13 15:33:32.218+01
257 |   | 55.5647222222 | 12.9733333 | MHM 12751 |   | Citytunnelprojektet delområde Hotelltomten |   | 2014-02-19 15:28:44.312+01
258 |   | 59.5261111 | 18.9977778 |   |   | Ägglösen |   | 2014-02-19 15:28:44.312+01
268 |   | 59.5927222219 | 16.4485111 |   |   | Västra Skälby |   | 2014-02-19 15:28:44.312+01
288 | 44 | 66.0204306 | 22.6298389 | Töre 405:2 |   | Töre 405:2 |   | 2014-02-19 15:28:44.312+01
289 |   | 59.5347222 | 18.5644444 |   |   | Norra Småholmen |   | 2014-02-19 15:28:44.312+01
291 |   | 65.9296833337 | 22.8561528 | Töre 510 |   | Kosjärv |   | 2014-02-19 15:28:44.312+01
292 | 50 | 66.0250167 | 22.6166667 | Töre 408:1 |   | Töre 408:1 |   | 2014-02-19 15:28:44.312+01
294 |   | 65.9783861114 | 19.1512028 |   |   | Åssjiejávrátje |   | 2014-02-19 15:28:44.312+01
305 |   | 59.6830555559 | 18.9266667 |   |   | Fåröarna |   | 2014-02-19 15:28:44.312+01
320 |   | 59.5152777778 | 18.7777778 |   |   | Bergskärit |   | 2014-02-19 15:28:44.312+01
328 | 25 | 59.6732250 | 17.8628361 | Odensala 402:1 |   | Odensala Raä 402 |   | 2014-02-19 15:28:44.312+01
337 | 15 | 59.6973222 | 18.4795028 | Skederid 190 | Settlement site | Skederid Raä 190 |   | 2014-02-19 15:28:44.312+01
345 |   | 61.1331666670 | 16.9196917 |   |   | Själstuga |   | 2014-02-19 15:28:44.312+01
350 |   | 59.5775000 | 18.9636111 |   |   | Stora Halmören |   | 2014-02-19 15:28:44.312+01
354 | 5 | 58.7519722 | 17.0113527778 | Nyköping 231:1 | Stadslager, ca 1150x1000 m (N-S), medeltida och yngre, i stadscentrum. | Åkroken |   | 2014-02-19 15:28:44.312+01
358 |   | 59.6833333330 | 18.9552778 |   |   | Marskärskobben |   | 2014-02-19 15:28:44.312+01
373 |   | 62.5760694448 | 12.5677750 | Härjedalen 169 |   | Hedningsgärdet |   | 2014-02-19 15:28:44.312+01
374 |   | 59.5655555556 | 18.9725000 |   |   | Stora Träskär |   | 2014-02-19 15:28:44.312+01
384 | 45 | 66.0217556 | 22.6267111 |   |   | Töre 422 |   | 2014-02-19 15:28:44.312+01
386 |   | 64.9952583 | 21.3126556 |   |   | Tåme |   | 2014-02-19 15:28:44.312+01

**Comment by Loer0022** [comment]
[MAL sites with corrected coordinates.xlsx](https://github.com/humlab-sead/sead_change_control/files/3988687/MAL.sites.with.corrected.coordinates.xlsx)

**Comment by roger-mahler** [comment]
@Loer0022 will create an SQL script this change.

**Comment by Loer0022** [comment]
The january milestone update for the MAL dataset mainly regard the geographical and macrofossil data in SEAD. The soil chemistry and bibliography will be updated hopefully towards the February milestone.

The January update and corrections made includes (see attached file):

- Adding coordinates to 53 sites (see above)
- Adding national_site_identifier to 2 sites
- Correction of spelling errors in tbl_locations and tbl_taxa_tree_master
- Correcting 53 sample names and adding date_sampled to a couple samples in tbl_physical_samples
- Correcting abundance for 7 posts and 80 posts containing either wrong species or genus

[GitHUB QA lookup sheet.xlsx](https://github.com/humlab-sead/sead_change_control/files/4152605/GitHUB.QA.lookup.sheet.xlsx)

**Comment by Loer0022** [comment]
@roger-mahler I sent the update query to your email since it wasn't possible to upload here, a bit later than anticipated. Mail me if there is some issues with the sql
