### ISSUE TITLE
Missing ceramics tables

### ISSUE THREAD

**Issue by MattiasSealander** [humlab-sead/sead_change_control#47]
Due to an error in registering the local ID in the wrong column during Excel preparation two tables in the ceramics data weren't imported into SEAD (tbl_sample_group_descriptions & tbl_sample_dimensions). This has been corrected and a new Excel prepped to go through the import procedure, which should fix the issue.

**Comment by roger-mahler** [comment]
Moving this to SEAD @2020.02 release. This needs to be investigated further since the records do seem to exist in the database but probably associated to wrong parent records.

**Comment by MattiasSealander** [comment]
sead_staging_test seems to have the full ceramics dataset. Is this based on the latest import file? I used a query calling on all ceramics tables and it seems to return the result without any issues, including group_descriptions and sample_dimensions.
