### ISSUE TITLE
Check that dataset submission entries created

### ISSUE THREAD

**Issue by visead** [humlab-sead/sead_change_control#49]
On creation of each bugs datasets, tbl_dataset_submissions entries need to be created automatically. 
Submission type as follows:
"submission_type_id";"submission_type";"description"
5;"Compilation into SEAD from another database";"Single dataset from another database submission into SEAD"

**Comment by roger-mahler** [comment]
See [20191222_DML_DATASET_SUBMISSION_UPDATE](https://github.com/humlab-sead/sead_change_control/blob/master/general/deploy/20191222_DML_DATASET_SUBMISSION_UPDATE.sql). This code must be verified/approved. The change is moved to SEAD 202002 release.

**Comment by roger-mahler** [comment]
To clarify: the question marks `????` in the last two insert statements in [20191222_DML_DATASET_SUBMISSION_UPDATE](https://github.com/humlab-sead/sead_change_control/blob/master/general/deploy/20191222_DML_DATASET_SUBMISSION_UPDATE.sql) need to be replaces by proper criterias.

**Comment by visead** [comment]
Changes in **bold** (at least they were supposed to be!) below. The new submission types need to be entered into tbl_dataset_submission_types

        /* MAL, Eriks */

        insert into tbl_dataset_submissions (dataset_id, submission_type_id, contact_id, date_submitted, notes)

        	select d.dataset_id, 7, 1, d.date_updated, **'Compilation into SEAD from primary source using Eriks Erikssons software'**

        	from tbl_datasets d

        	left join tbl_dataset_submissions s using (dataset_id)

        	where TRUE

        	  and s.dataset_submission_id is null

        	  and d.master_set_id in (2)

              **and d.method_id<>14**;         /* = Not Pollen */



        /* Pollen */

        insert into tbl_dataset_submissions (dataset_id, submission_type_id, contact_id, date_submitted, notes)

        	select d.dataset_id, 15, 1, d.date_updated, **'Single dataset from another database submission into SEAD via Tilia** software'

        	from tbl_datasets d

        	left join tbl_dataset_submissions s using (dataset_id)

        	where TRUE

        	  and s.dataset_submission_id is null

        	  and d.master_set_id in (2)

              **and d.method_id=14**; /* = Pollen */
