### ISSUE TITLE
20200422_DML_MAL_TAXA_SP_SPP_QOS_UPDATE

### ISSUE THREAD

**Issue by Loer0022** [humlab-sead/sead_change_control#51]
When going through the MAL macrofossil dataset I noticed that at times there are more than one instance of sp. and spp. but without the punctuation (i.e. sp and spp). It appears that no sample is using sp but 173 posts are using spp, I will make a query to update these today

We should look into if there are any connections with the older sp and spp instances within the database, I suspect it might be connected with bibliography or perhaps ecology.

Is there a possibility to remove these posts after they are verified to not be connected with anything?

Also, we need to look into adding a sp. and spp. for every plant species that does not already have them. I noticed three plant genus that lack these already (Silene (id 391), Viola (id 1070) and Empetrum (id 490)) that are given a random (?) species instead when exporting data which isn't good.

**Comment by Loer0022** [comment]
Tbl_taxa_tree_master

![image](https://user-images.githubusercontent.com/55080011/73753018-3df42900-4762-11ea-973d-3cffef3e176a.png)

**Comment by Loer0022** [comment]
@visead

**Comment by visead** [comment]
Probably not - but check with SQL

**Comment by Loer0022** [comment]
As requested from previous meetings this should be divided into two parts,

1.  Check to see if there are any connections with the old and erronous sp/spp found in tbl_taxa_tree_master before removing them. 

If there are connections to e.g. bibliograpgy this should be reconnected with a minor update to the corresponding sp./spp. of the same Genus (e.g. Chenopodium sp -> Chenopodium sp.), if the Genus lacks a sp./spp. but is using a sp/spp then it can be updated to have the punctuation instead.

2. Update those Genus that are still using sp/spp to sp./spp. (update query pending for February milestone)

3. Add sp./spp. to all Genus currently lacking such instances - all plants and beetles need to have such annotations for when there is an unknown species belonging to a specific Genus (e.g. Hordeum sp.) found in samples.

**Comment by Loer0022** [comment]
1. Check to see if there are any connections with the old and erronous sp/spp found in tbl_taxa_tree_master before removing them.

Ran the querry bellow to check if sp/spp doubles were connected with any tables to make sure that removing them would not cause issues down the line. It appears that the species "sp" was in general not in use and has been correctly ingested again later on. Some MAL data used "spp", however, updating them by adding a period "spp." will solve all issues regarding 15 genus.

Two genus needs to update its connections before removing the doublettes - update querry will be attached later today - Potentilla spp. (taxon_id 18171) and Ranunculus spp. (taxon_id 18182).

-----

```sql

select string_agg(Chr(10), 'select ''' || table_name || ''' as table_name, taxon_id from  ' || table_name || ' UNION ')
from clearing_house.view_foreign_keys
where schema_name = 'public'
and column_name = 'taxon_id'

with all_references as (
                          select 'tbl_dating_material' as table_name, taxon_id from  tbl_dating_material UNION
                          select 'tbl_ecocodes' as table_name, taxon_id from  tbl_ecocodes UNION
                          --select 'tbl_imported_taxa_replacements' as table_name, taxon_id from  tbl_imported_taxa_replacements UNION
                          select 'tbl_mcr_names' as table_name, taxon_id from  tbl_mcr_names UNION
                          select 'tbl_mcr_summary_data' as table_name, taxon_id from  tbl_mcr_summary_data UNION
                          select 'tbl_mcrdata_birmbeetledat' as table_name, taxon_id from  tbl_mcrdata_birmbeetledat UNION
                          select 'tbl_rdb' as table_name, taxon_id from  tbl_rdb UNION
                          select 'tbl_species_associations' as table_name, taxon_id from  tbl_species_associations UNION
                          select 'tbl_taxa_common_names' as table_name, taxon_id from  tbl_taxa_common_names UNION
                          select 'tbl_taxa_images' as table_name, taxon_id from  tbl_taxa_images UNION
                          select 'tbl_taxa_measured_attributes' as table_name, taxon_id from  tbl_taxa_measured_attributes UNION
                          select 'tbl_taxa_reference_specimens' as table_name, taxon_id from  tbl_taxa_reference_specimens UNION
                          select 'tbl_taxa_seasonality' as table_name, taxon_id from  tbl_taxa_seasonality UNION
                          select 'tbl_taxa_synonyms' as table_name, taxon_id from  tbl_taxa_synonyms UNION
                          select 'tbl_taxonomic_order' as table_name, taxon_id from  tbl_taxonomic_order UNION
                          select 'tbl_taxonomy_notes' as table_name, taxon_id from  tbl_taxonomy_notes UNION
                          select 'tbl_text_biology' as table_name, taxon_id from  tbl_text_biology UNION
                          select 'tbl_text_distribution' as table_name, taxon_id from  tbl_text_distribution UNION
                          select 'tbl_text_identification_keys' as table_name, taxon_id from  tbl_text_identification_keys

) select *
  from tbl_taxa_tree_master b
  left join all_references a using (taxon_id)
  where a.taxon_id is null

```

-----

Below is a list of taxon_id that are douplicattes that doesn't have any connection to other tables making them safe to remove.

taxon_id | author_id | date_updated | genus_id | species | genus_name
-- | -- | -- | -- | -- | --
18257 | NULL | 2014-02-19 14:28:44.312+00 | 778 | sp | Alopecurus
18094 | NULL | 2013-11-13 14:33:32.218+00 | 938 | sp | Amelanchier
18207 | NULL | 2014-02-19 14:28:44.312+00 | 485 | sp | Arctostaphylos
18068 | NULL | 2013-05-13 09:29:56.070308+00 | 785 | sp | Arrhenatherum
18157 | NULL | 2013-11-13 14:33:32.218+00 | 400 | sp | Atriplex
18163 | NULL | 2013-11-13 14:33:32.218+00 | 299 | sp | Brassica
18051 | NULL | 2013-05-13 09:29:56.070308+00 | 791 | sp | Bromus
18048 | NULL | 2013-05-13 09:29:56.070308+00 | 303 | sp | Camelina
18187 | NULL | 2014-02-19 14:28:44.312+00 | 356 | sp | Campanula
18014 | NULL | 2013-05-13 09:29:56.070308+00 | 454 | sp | Carex
18152 | NULL | 2013-11-13 14:33:32.218+00 | 9795 | sp | Caryophyllaceae
18125 | NULL | 2013-11-13 14:33:32.218+00 | 371 | sp | Cerastium
18013 | NULL | 2013-05-13 09:29:56.070308+00 | 404 | sp | Chenopodium
18206 | NULL | 2014-02-19 14:28:44.312+00 | 147 | sp | Cirsium
18126 | NULL | 2013-11-13 14:33:32.218+00 | 947 | sp | Crataegus
18160 | NULL | 2013-11-13 14:33:32.218+00 | 805 | sp | Danthonia
18058 | NULL | 2013-05-13 09:29:56.070308+00 | 810 | sp | Echinochloa
18015 | NULL | 2013-05-13 09:29:56.070308+00 | 9777 | sp | Echinochloa/Setaria
18066 | NULL | 2013-05-13 09:29:56.070308+00 | 457 | sp | Eleocharis
18237 | NULL | 2014-02-19 14:28:44.312+00 | 891 | sp | Fallopia
18080 | NULL | 2013-11-13 14:33:32.218+00 | 820 | sp | Festuca
18223 | NULL | 2014-02-19 14:28:44.312+00 | 558 | sp | Fumaria
18006 | NULL | 2013-05-13 09:29:56.070308+00 | 613 | sp | Galeopsis
18022 | NULL | 2013-05-13 09:29:56.070308+00 | 975 | sp | Galium
18041 | NULL | 2013-05-13 09:29:56.070308+00 | 521 | sp | Genista
18158 | NULL | 2013-11-13 14:33:32.218+00 | 179 | sp | Helianthus
18145 | NULL | 2013-11-13 14:33:32.218+00 | 9794 | sp | Hordeum/Avena
18139 | NULL | 2013-11-13 14:33:32.218+00 | 9793 | sp | Hordeum/Triticum
18062 | NULL | 2013-05-13 09:29:56.070308+00 | 1029 | sp | Hyoscyamus
18131 | NULL | 2013-11-13 14:33:32.218+00 | 603 | sp | Juncus
18137 | NULL | 2013-11-13 14:33:32.218+00 | 450 | sp | Juniperus
18141 | NULL | 2013-11-13 14:33:32.218+00 | 619 | sp | Lamium
18078 | NULL | 2013-05-16 08:39:58.584644+00 | 837 | sp | Lolium
18038 | NULL | 2013-05-13 09:29:56.070308+00 | 604 | sp | Luzula
18037 | NULL | 2013-05-13 09:29:56.070308+00 | 741 | sp | Melampyrum
18113 | NULL | 2013-11-13 14:33:32.218+00 | 534 | sp | Ononis
18067 | NULL | 2013-05-13 09:29:56.070308+00 | 894 | sp | Persicaria
18143 | NULL | 2013-11-13 14:33:32.218+00 | 763 | sp | Picea
18081 | NULL | 2013-11-13 14:33:32.218+00 | 764 | sp | Pinus
18149 | NULL | 2013-11-13 14:33:32.218+00 | 855 | sp | Poa
18140 | NULL | 2013-11-13 14:33:32.218+00 | 895 | sp | Polygonum
18090 | NULL | 2013-11-13 14:33:32.218+00 | 983 | sp | Populus
18133 | NULL | 2013-11-13 14:33:32.218+00 | 905 | sp | Potamogeton
17998 | NULL | 2013-05-13 09:29:56.070308+00 | 959 | sp | Potentilla
18136 | NULL | 2013-11-13 14:33:32.218+00 | 959 | spp | Potentilla
18155 | NULL | 2013-11-13 14:33:32.218+00 | 634 | sp | Prunella
18112 | NULL | 2013-11-13 14:33:32.218+00 | 551 | sp | Quercus
18119 | NULL | 2013-11-13 14:33:32.218+00 | 929 | spp | Ranunculus
18056 | NULL | 2013-05-13 09:29:56.070308+00 | 746 | sp | Rhinanthus
18096 | NULL | 2013-11-13 14:33:32.218+00 | 342 | sp | Rorippa
18063 | NULL | 2013-05-13 09:29:56.070308+00 | 964 | sp | Rubus
18029 | NULL | 2013-05-13 09:29:56.070308+00 | 9780 | sp | Rubus subg. Rubus
18031 | NULL | 2013-05-13 09:29:56.070308+00 | 897 | sp | Rumex
18099 | NULL | 2013-11-13 14:33:32.218+00 | 979 | sp | Ruppia
18057 | NULL | 2013-05-13 09:29:56.070308+00 | 390 | sp | Scleranthus
18046 | NULL | 2013-05-13 09:29:56.070308+00 | 863 | sp | Secale
18117 | NULL | 2013-11-13 14:33:32.218+00 | 9791 | sp | Secale/Triticum
18027 | NULL | 2013-05-13 09:29:56.070308+00 | 865 | sp | Setaria
18216 | NULL | 2014-02-19 14:28:44.312+00 | 9805 | sp | Setaria/Danthonia
18204 | NULL | 2014-02-19 14:28:44.312+00 | 9799 | sp | Setaria/Echinochloa
18129 | NULL | 2013-11-13 14:33:32.218+00 | 391 | sp | Silene
18084 | NULL | 2013-11-13 14:33:32.218+00 | 1041 | sp | Solanum
18000 | NULL | 2013-05-13 09:29:56.070308+00 | 392 | sp | Spergula
18110 | NULL | 2013-11-13 14:33:32.218+00 | 640 | sp | Stachys
18019 | NULL | 2013-05-13 09:29:56.070308+00 | 545 | sp | Trifolium
18089 | NULL | 2013-11-13 14:33:32.218+00 | 1063 | sp | Urtica
18130 | NULL | 2013-11-13 14:33:32.218+00 | 1020 | sp | Verbascum
18101 | NULL | 2013-11-13 14:33:32.218+00 | 1021 | sp | Veronica
18004 | NULL | 2013-05-13 09:29:56.070308+00 | 548 | sp | Vicia
18173 | NULL | 2014-02-19 14:28:44.312+00 | 9798 | sp | Vicia/Pisum
18042 | NULL | 2013-05-13 09:29:56.070308+00 | 1070 | sp | Viola

**Comment by Loer0022** [comment]
2. **Update those species that are still using sp/spp in tbl_abundances to sp./spp. (update query pending for February milestone).**

Checking through the SP/SPP occurrences there were only 11 posts in need of an update – all connected to spp regarding the genus Potentilla and Ranunculus. These should be updated prior to the removal of any of the other erroneous instances to ensure that no errors occur down the line. Furthermore, 17 posts will be updated adding a punctuation to the spp solving part of the issue of properly documenting plant species.

See attached file for updates.

[SP SPP lookup table.xlsx](https://github.com/humlab-sead/sead_change_control/files/4408343/SP.SPP.lookup.table.xlsx)

Once these updates have been made the following posts can also be removed from the database as they are doubles of already existing posts not containing the punctuation error.


taxon_id | author_id | date_updated | genus_id | species
-- | -- | -- | -- | --
18136 | NULL | 2013-11-13   14:33:32.218+00 | 959 | spp
18119 | NULL | 2013-11-13   14:33:32.218+00 | 929 | spp

**Comment by Loer0022** [comment]
3. Add sp./spp. to all Genus currently lacking such instances - all plants and beetles need to have such definitions for when there is an unknown species belonging to a specific Genus (e.g. Hordeum sp.) found in samples.

This is not an urgent issue and will not be solved by actively adding sp./spp. to all species. Rather this issue will solve itself pragmatically when new species are being added that lack these definitions, meaning that tbl_taxa_tree_master will gradually include these instances over time.

**Comment by roger-mahler** [comment]
Third item moved to separate issue #68.
