### ISSUE TITLE
Import Bugs database v20200219

### ISSUE THREAD

**Issue by roger-mahler** [humlab-sead/sead_change_control#61]
New data import of Bugs data. This will be the first incremental update of the Bugs data.

**Comment by roger-mahler** [comment]
The incremental data set of the @2020.02 bugs import of BugsCEP v20200219 has been compiled into change request [20200313_DML_BUGSDATA_20200219](https://raw.githubusercontent.com/humlab-sead/sead_change_control/master/bugs/deploy/20200313_DML_BUGSDATA_20200219.sql).

This data needs a sanity check.

**Comment by roger-mahler** [comment]
Are these numbers reasonable @visead?

**Comment by visead** [comment]
Yes, they look reasonable in relation to the changes I made to the sample dates and depths, as well as new data from Paul.

**Comment by roger-mahler** [comment]
CR  [20200313_DML_BUGS_IMPORT_PUBLIC_20200219](#62)
