### ISSUE TITLE
Isotope: Remaining errors in Isotope data

### ISSUE THREAD

**Issue by roger-mahler** [humlab-sead/sead_change_control#63]
### Remaining errors in Isotope data:

- Reference to missing `method_id`:
    - `method_id` 23 in `tbl_isotope_measurement` 
    - `method_id` 5 in `tbl_sample_groups `
- Reference to missing `sample_type_id`:
    - `method_id` 15 in `tbl_physical_samples`

**Comment by MGE4** [comment]
There were no other changes to the data more then the once mentioned above.

**Comment by roger-mahler** [comment]
Grejt! Closing issue.
