### ISSUE TITLE
20200422_DML_MAL_QOS_UPDATE_02

### ISSUE THREAD

**Issue by Loer0022** [humlab-sead/sead_change_control#66]
The MAL soilchemical dataset provides a relatively good quality of data to the end-users, with the exception being missing samples resulting in a considerable loss of data for large sites. There were some errors when importing data to SEAD which resulted in the wrong measurements being ingested, however, this is mainly related to large sites with 500 or more posts in them.

Bellow is a list of the posts being updated (see attached file for comments),

-  **tbl_physical_samples** - added date sampled for 14 samples and corrected 254 sample names
-  **tbl_sample_groups** - corrected a mixup between two sample groups that were missplaced to the wrong site of similar name (RAÄ 1639 & RAÄ 1636)
- **tbl_sites** - updated various missing/erronous information for 12 sites. This table could need further QA
- **tbl_measured_values** - corrected 91 measured values where import errors had occured

[MAL QA soilchem data - Part II.xlsx](https://github.com/humlab-sead/sead_change_control/files/4380860/MAL.QA.soilchem.data.-.Part.II.xlsx)

**Comment by Loer0022** [comment]
[MAL QA soilchem data - Part II.xlsx](https://github.com/humlab-sead/sead_change_control/files/4380834/MAL.QA.soilchem.data.-.Part.II.xlsx)

**Comment by roger-mahler** [comment]
Same Excel with added DDL statements.

[MAL.QA.soilchem.data.-.Part.II.xlsx](https://github.com/humlab-sead/sead_change_control/files/4516793/MAL.QA.soilchem.data.-.Part.II.xlsx)
