### ISSUE TITLE
Change filter item name

### ISSUE THREAD

**Issue by visead** [humlab-sead/sead_change_control#86]
Filter: Master datasets
Current name: Sample data Isotopes

New name: Archaeological Research Laboratory (Stockholm/KFL)

**Comment by johanvonboer** [comment]
This is information stored in the db, so it needs to be changed there by applying an SQL-patch in Squitch - I think? I'm not sure how that system works, but I transferred this issue to that repo.

**Comment by roger-mahler** [comment]
Retrospective change from @2019.12
